name: Publish extension

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install packages
        run: |
          curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm
          pnpm install

      - name: Run checks
        run: |
          pnpm tsc
          pnpm prettier-check
          pnpm lint
          pnpm test

      - name: Run integration tests
        run: pnpm test-intgr

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-failures
          path: tmp/
          if-no-files-found: warn

      - name: publish extension
        run: pnpm publish
